import { Inter } from 'next/font/google'
import './globals.css'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import dynamic from 'next/dynamic'
import { ParentIdProvider } from '@/utils/Context'
import MainLayout from '@/components/MainLayout'

export const metadata = {
  title: 'CLOUD CABINET',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <ParentIdProvider>
          <body className="bg-green-200">
            <MainLayout>{children}</MainLayout>
          </body>
        </ParentIdProvider>
      </UserProvider>
    </html>
  )
}
