import { Inter } from 'next/font/google'
import './globals.css'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import SideNav from '@/components/SideNav'
import Home from '@/components/Home'
import Storage from '@/components/Storage'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <div className=" gap-5  flex">
            <SideNav />
            <div className=" grid grid-cols-1 md:grid-cols-3 w-full">
              <div className=" sm:col-span-2">{children}</div>
              <div className=" p-5 bg-white">
                <Storage />
              </div>
            </div>
          </div>
        </body>
      </UserProvider>
    </html>
  )
}
