import { Inter } from 'next/font/google'
import './globals.css'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import SideNav from '@/components/SideNav'

import Storage from '@/components/Storage'
import { ContextProvider, ParentIdProvider } from '@/utils/Context'

export const metadata = {
  title: 'CLOUD CABINET',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <ParentIdProvider>
          <body className=" bg-gray-400">
            <div className=" gap-5  flex">
              <SideNav />
              <div className=" grid grid-cols-1 p-2 sm:p-0 md:grid-cols-3 w-full gap-3">
                <div className="col-span-2">{children}</div>

                <div className=" p-5 bg-white">
                  <Storage />
                </div>
              </div>
            </div>
          </body>
        </ParentIdProvider>
      </UserProvider>
    </html>
  )
}
